pimcore:
    general:
        timezone: Europe/Berlin
        path_variable: ''
        domain: ''
        redirect_to_maindomain: false
        language: en
        debug_admin_translations: false
        show_cookie_notice: false
        valid_languages: 'en,id'
        fallback_languages:
            en: ''
            id: ''
        default_language: id
        disable_usage_statistics: false
        instance_identifier: ''
    documents:
        versions:
            days: null
            steps: 10
        default_controller: default
        default_action: default
        error_pages:
            default: /404
        create_redirect_when_moved: false
        allow_trailing_slash: 'no'
        generate_preview: true
    objects:
        versions:
            days: null
            steps: 10
    assets:
        versions:
            days: null
            steps: 10
        icc_rgb_profile: ''
        icc_cmyk_profile: ''
        hide_edit_image: false
        disable_tree_preview: false
    services:
        google:
            client_id: ''
            email: ''
            simple_api_key: ''
            browser_api_key: ''
    full_page_cache:
        enabled: false
        lifetime: null
        exclude_patterns: ''
        exclude_cookie: ''
    httpclient:
        adapter: Socket
        proxy_host: ''
        proxy_port: ''
        proxy_user: ''
        proxy_pass: ''
    email:
        sender:
            name: ''
            email: ''
        return:
            name: ''
            email: ''
        method: null
        debug:
            email_addresses: ''
    newsletter:
        sender:
            name: ''
            email: ''
        return:
            name: ''
            email: ''
        method: null
        debug: null
        use_specific: false
    webservice:
        enabled: false
    applicationlog:
        mail_notification:
            send_log_summary: false
            filter_priority: null
            mail_receiver: ''
        archive_treshold: '30'
        archive_alternative_database: ''
pimcore_admin:
    branding:
        color_login_screen: ''
        color_admin_interface: ''
        login_screen_custom_image: ''
swiftmailer:
    mailers:
        pimcore_mailer:
            transport: null
            delivery_addresses: {  }
            host: ''
            username: ''
            password: null
            port: ''
            encryption: null
            auth_mode: null
        newsletter_mailer:
            transport: null
            delivery_addresses: {  }
            host: ''
            username: ''
            password: null
            port: ''
            encryption: null
            auth_mode: null
