---
- hosts: all
  tasks:
    - name: start nginx
      service:
        name: nginx
        state: started
      become: yes
    - name: copy the nginx config file and restart nginx
      copy:
        src: /var/www/html/bfi/.ansible-deployment/bfi.conf
        dest: /etc/nginx/sites-available/bfi.conf
      become: yes
    - name: create symlink
      file:
        src: /etc/nginx/sites-available/bfi.conf
        dest: /etc/nginx/sites-enabled/bfi
        state: link
      become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
