version: "3.7"

services:
  web:
    image: nginx:latest
    container_name: bfi-nginx
    ports:
      - "80:80"
      - "8085:8085"
      - "8086:8086"
    volumes:
      - /var/www/html/bfi/docroot:/var/www/html/docroot
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/myEnterprise.conf:/etc/nginx/conf.d/myEnterprise.conf
      - ./nginx/msds.conf:/etc/nginx/conf.d/msds.conf
      - ./logs/nginx:/var/log/nginx
      - ./logs/apps:/var/www/logs
      - /sock:/sock
    networks:
      docker:
        ipv4_address: 172.18.0.2
  php:
    image: rizasalt/bfi:latest
    stdin_open: true
    tty: true
    container_name: bfi-container
    working_dir: /var/www/html
    volumes:
      # - /var/www/html/telkomsel-b2b:/var/www/html
      - /var/www/html/bfi/docroot:/var/www/html/docroot
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php-fpm/zzz-docker.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf
      - /sock:/sock
      - /usr/local/bin/composer:/usr/local/bin/composer
      - ./logs/apps:/var/www/storage/log
    networks:
      docker:
        ipv4_address: 172.18.0.3
  adminer:
    image: adminer:latest
    container_name: b2b-adminer
    # restart: always
    ports:
      - 8080:8080
    networks:
      docker:
        ipv4_address: 172.18.0.4

networks:
  docker:
    external:
      name: default_docker

volumes:
  cgroup:
